
== Future Work

The next step the OGC should take is to establish a common approach to asynchronous Web APIs. Ideally, a Pub-Sub extension to OGC API-Common. This would provide a standard API module which could be extended to define Pub-Sub capabilities for existing and developmental OGC Web API standards.

The family of OGC Web API Standards is built on the architecture patterns represented by OpenAPI. AsyncAPI is an extension of OpenAPI. So the first step should be to identify or develop a JSON schema which integrates OpenAPI and AsyncAPI. This API definition language will be used to guide further standards activities.

Once an API definition language has been identified, the next step will be to develop the directions on how that language should be applied to creating Pub-Sub extensions to OGC Web APIs. These directions would be documented as a draft extension to OGC API-Common.

The draft Pub-Sub extension would then be evaluated against existing and planned asynchonous OGC Web API and Web Service standards. Based on this analysis, the draft extension would be refined to maximize its' effectiveness and utility.

The final step would be to publish the refined specification as a new OGC Web API module.

Action: The OGC Web API-Common SWG Charter is currently under review. This work item should be added to the program of work for that SWG. 


