[[references]]
== References

The following documents are referenced in this document.
For dated references, subsequent amendments to, or revisions of, any of these publications do not apply.
For undated references, the latest edition of the normative document referred to applies.


* OGC 06-121r3, OGC® Web Services Common Specification, version 1.1.0 (9 February 2007)
* OGC 13-131, OGC® Publish/Subscribe Interface Standard 1.0 - Core
* OGC 13-133, OGC® Publish/Subscribe Interface Standard 1.0 - SOAP Protocol Binding Extension
* OGC 13-132, OGC® Publish/Subscribe Interface Standard 1.0 - RESTful Protocol Binding Extension (draft, in progress)
* OGC 07-006r1, OpenGIS® Catalogue Services Specification, version 2.0.2, corrigendum 2
* OGC 07-045, OpenGIS® Catalogue Services Specification 2.0.2 - ISO Metadata Application Profile, version 1.0
* OGC 07-110r4, CSW-ebRIM Registry Service - Part 1: ebRIM profile of CSW, version 1.0.1, corrigendum 1
* OGC 07-144r4, CSW-ebRIM Registry Service - Part 2: Basic extension package, version 1.0.1, corrigendum 1
* OGC 08-103r2, CSW-ebRIM Registry Service - Part 3: Abstract Test Suite, version 1.0.1
* OGC 16-137r2, Testbed-12 PubSub / Catalog Engineering Report (12 May 2017)
