== Terms and definitions
[[section:abbreviations]]

For the purposes of this report, the definitions specified in Clause 4 of the
http://portal.opengeospatial.org/files/?artifact_id=38867[OWS Common Implementation Standard [OGC 06-121r9]] shall apply.
In addition, the following terms and definitions apply.

* Broker | Brokering Publisher

  Intermediary between Subscribers and other Publishers which have been previously registered with the broker. The broker is not the original producer of messages, but only acts as a message middleman, re-publishing messages received from other Publishers and decoupling them from their Subscribers

* Message

  A container within which data (such as XML, binary data, or other content) is transported. Messages may include additional information beyond data, including headers or other information used for routing or security purposes

* Publish–subscribe pattern

  A messaging pattern where message publishers categorize and send a message to a class of subscribers without knowledge of subscribers.
  Similarly, subscribers express interest in one or more classes of messages and receive them without knowledge of their publishers.

* Publication

  A uniquely identified aggregation of messages published by a Publisher over time. A Publisher may offer any number of publications that Subscribers may subscribe to

* Publisher

  An entity that offers publications to Subscribers; supports subscription management (subscribe, unsubscribe) and is responsible for filtering and matching messages of interest to active subscriptions

* Receiver

  An entity that receives messages from Senders; may (but need not) be the original Subscriber

* Reliable Publisher

  A publisher of messages that offers capabilities to detect and recover from message delivery losses, whether caused by network failures, software failures, hardware failures, or other causes

* Sender

  An entity that sends messages to Receivers; may (but need not) be the initial creator/producer of the data in the message payload

* Subscriber

  An entity that creates a subscription at a Publisher; may (but need not) be the Receiver of delivered messages

* Subscription

  Expression of interest in all or part of a publication offered by a Publisher. When a subscription has been created, the Publisher delivers messages that match the subscription criteria to the Receiver defined in the subscription

===	Abbreviated terms

// * API	Application Program Interface
// * COM	Component Object Model
// * CORBA	Common Object Request Broker Architecture
// * COTS	Commercial Off The Shelf
// * DCE	Distributed Computing Environment
// * DCOM	Distributed Component Object Model
* ATC Air Traffic Control
* ATM Air Traffic Management
* ADS–B Automatic Dependent Surveillance–Broadcast
* CFP Call for Participation
* CSW Catalogue Service for the Web
* CHI Computer-Human Interface
* DDS Data Distribution Service
* DIS Distributed Interactive Simulation
* DWG Domain Working Group
* ERAM En Route Automation Modernization
* FAA Federal Aviation Administration
* HLA High-Level Architecture
* HMI Human-Machine Interface
* HTTP Hypertext Transfer Protocol
* IEEE	Institute of Electrical and Electronics Engineer
* InterCOM	Intercommunication
* IoT Internet of Things
// * IDL	Interface Definition Language
* MEP Message Exchange Pattern
* MQTT Message Queuing Telemetry Transport
* OAI-PMH Open Archives Initiative Protocol for Metadata Harvesting
* OASIS Organization for the Advancement of Structured Information Standards
* OData Open Data Protocol
* OGC Open Geospatial Consortium
* OMG Object Management Group
* OpenWIS Open WMO Information system
* OpenAPI Open API Standard
* OWS OGC Web Services
* PSR Primary Surveillance Radar
* PubSub Publish–subscribe
* QoS Quality of Service
* RFQ Request for Quotation
* SOS Sensor Observation Service
* SSE Server-Sent Events
* SSR Secondary Surveillance Radar
* STARS Standard Terminal Automation Replacement System
* SWG Standards Working Group
* TRACON Terminal Radar Approach CONtrol
* UAS Unmanned Aviation System
* URL Uniform Resource Locator
* UML Unified Modelling Language
* VoIP Voice over Internet Protocol
* VRR Voice Recognition/Response
* WIS WMO Information system
* WPS Web Processing Service
* WCS Web Coverage Service
* WFS web Feature Service
* XML eXtensible Markup Language


===	UML notation

Most diagrams that appear in this document are presented using the UML 2 static structure diagram, as described in Subclause 5.2 of [OGC 06-121r9].

All classes in this document are extensible and may be extended with application- or
domain-specific content via Extension blocks.

NOTE: The UML shown in this document is considered conceptual and abstract,
and should not be interpreted as an implementation strategy for bindings that extend and
implement a standard. For example, TM_Instant from ISO 19108 may be used to represent
time instants for conceptual clarity, but bindings and implementations of this document
may realize TM_Instant as a GML TimeInstant, an ISO 8601 date string, or any other
representation that is consistent with TM_Instant.
