== PubSub in OGC SensorThings

OGC SensorThings API is a standard for interconnecting the Internet of Things (IoT) devices, data, and applications over the Web. OGC SensorThings API has two main parts: the sensing part that focuses on heterogeneous IoT sensor systems, and the Tasking part focused on IoT actuators and tasking devices.

OGC SensorThings API is following ODATA for managing the sensing resources. Thus, it has a REST-like API and supports HTTP CRUD operations (GET, POST, PATCH, DELETE) and ODATA query options (select, expand, filter, orderby, top, skip) for data retrieval.

In addition to supporting HTTP, OGC SensorThings API has the extension for supporting MQTT to create and real-time retrieval of sensor Observations.

MQ Telemetry Transport, known as MQTT, is an OASIS standard. MQTT is an extremely lightweight publish-subscribe messaging protocol designed explicitly for resource-constrained IoT devices. The main concepts are topic and publish and subscribe functions. When a new message is published to a topic, anyone subscribing to that topic will receive a notification including that message.

OGC SensorThings API is adopting MQTT protocol and defines a topic structure to create and receive notifications from sensor Observations. The topic structure for OGC SensorThings API MQTT extension is following its HTTP resource path. It means that the topic used for creating Observation through MQTT is identical to the HTTP URL that is used for the POST and creating Observations.
Examples of these resource paths are *_v1.0/Observations_* and *_v1.0/Datastreams(id)/Observations_*. Similarly, accessing those URLs using HTTP GET would result in retrieving sensor Observations, while subscribing to those as topics means receiving notifications for those Observations in real-time.

Here is a summary of lessons learnt from MQTT adoption is OGC SensorThings API that might be applicable to any RESTful API:

*	Each RESTful API has a potential for MQTT binding to receive updates for a resource collection
**	The topic would be the resource GET URL
**	The payload will be the same as the content of HTTP GET
**	Whenever there is a new resource, it will be published to the resource GET URL topic
*	For any RESTful API, to create a resource, MQTT can be an option just like HTTP POST
**	The topic will be the same as the POST topic
**	The payload will be the same as the POST payload
**	The service would subscribe to the topics
**	Once it receives the payload, it uses the same process as POST to create the resource

=== OGC IMIST IOT Pilot
OGC Incident Management Information Sharing Internet of Things Pilot Project (https://www.ogc.org/projects/initiatives/imisiot<IMIS IoT Pilot>) depicts an incident fire, law enforcement, and emergency medical units must deploy, discover and integrate various sensors and platforms to gain situational awareness. In that pilot,  MQTT topics were defined to contain the resource path together with $filter query options. Then the Observation that is published to that topic was filtered by the criteria defined in the topic. In this way, rules can be defined to notify subscribers about specific conditions that happen, such as when the carbon dioxide reading for first responders is higher than a threshold and considered dangerous.
Example of the topic would be *_v1.0/Datastreams(id)/Observations?$filter=result gt 100_*.
IMIS is a pilot implementation and could be a starting point for OGC SensorThings API potential part 3, rules engine.
This was a pilot implementation and could be a starting point for OGC SensorThings API potential part 3, rules engine.
